### ISSUE TITLE
routes/getlinks.js issue on line 76

### ISSUE THREAD

**Issue by nedbaker12** [Thanatoslayer6/Himovies-unnoficial-api#1]
**UnhandledPromiseRejectionWarning: Error: Error: TypeError: Cannot read property '1' of null**
this.RecaptchaNumber = new RegExp(/recaptchaNumber = '(.*?)'/gm).exec(resp)[1],
RegExp cant find anything as recaptchaNumber in the resp . Please fix it thanks.

**Comment by Thanatoslayer6** [comment]
Good day! this issue has been resolved please check out the latest commit: f8e4dcec2eac344cde49decfdba700f10fc2c445
